- hosts: all
  name: Configure `wpa_supplicant.service` to run a debug version of the executable.
  gather_facts: no
  vars:
    ansible_become: yes
  tasks:
    - include_role:
        name: wpa_supplicant.debug
